### ISSUE TITLE
string-strip-html doc

### ISSUE THREAD

**Issue by Trigonometric** [codsen/codsen.com#1]
![image](https://user-images.githubusercontent.com/28106907/112423110-05038300-8d6d-11eb-9ba7-26c9652d2ebf.png)
Aren't these two identical calls returning different results?

**Comment by revelt** [comment]
hi! You're right! Sorry about that, I added more examples and updated the site this morning to fix. It was a stale `opts.returnRanges` key, removed previously, but example was not adapted. Good spot!
